name: Build flashable kernel (AOSP renoir)

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source Code
      uses: actions/checkout@v3
      with:
        github-server-url: 'https://github.com'
        repository: zeroXone-github/android_kernel_xiaomi_sm8350
        ref: lineage-21
        path: kernel-srcroot
    
    - name: Setup Kernel SU
      run: |
        cd kernel-srcroot
        git config --global user.email "you@example.com"
        git config --global user.name "zeroXone-github"
        cd drivers
        ln -sf ../KernelSU/kernel/ kernelsu
        git add .
        git commit -m "Blump up KSU for NonGKI kernel"
        git push origin
